/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 frog.gltf --transform
Author: Vie Dinh (https://sketchfab.com/yenvydinh2295)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-cute-frog-tin-1d0d16aef9d749e2822b0d97c184f4eb
Title: Little Cute Frog Tin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/frog-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Frog_low_ECH_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Circle003_LASEN_0.geometry} material={materials.LASEN} position={[323, -21.26, 501.07]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Circle004_SENHOA_0.geometry} material={materials.SENHOA} position={[183.84, -19.16, 407.07]} rotation={[-Math.PI / 2, 0, 0]} scale={31.7} />
        <mesh geometry={nodes.Circle_Water_0.geometry} material={materials.Water} position={[0, 0, 131.67]} rotation={[Math.PI / 2, 0, 0]} scale={[-606.48, 606.48, 606.48]} />
      </group>
    </group>
  )
}

useGLTF.preload('/frog-transformed.glb')
